version: '3.8'

services:
  # Frontend served by nginx (same as production)
  frontend:
    image: nginx:alpine
    ports:
      - "3500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # Backend service
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      - FLASK_PORT=5100
      - FLASK_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=${REDIS_HOST:-GZCRedis.redis.cache.windows.net}
      - REDIS_PORT=${REDIS_PORT:-6380}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FIX_SOCKET_HOST=fixapi-nysim1.fxspotstream.com
      - FIX_SOCKET_PORT=9001
      - FIX_SENDER_COMP_ID=T_GCMFX_MD
      - FIX_TARGET_COMP_ID=FSS
    volumes:
      - ./app/backend:/app
    working_dir: /app
    command: python run.py

networks:
  default:
    name: gzc-intel-network