
services:
  backend:
    build: .
    container_name: fxspotstream-backend
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ../fx-client
      dockerfile: Dockerfile
    container_name: fxspotstream-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
