#!/bin/bash

echo "🔍 Debugging Bloomberg Component Registration"
echo "============================================"

echo "1. Checking if containers are running..."
docker-compose -f docker-compose.local.yml ps

echo -e "\n2. Opening browser console to check component registration..."
echo "   Open http://localhost:3500"
echo "   Press F12 to open DevTools Console"
echo "   Run this command in console:"
echo ""
echo "   // Check Bloomberg component registration"
echo "   window.__componentDebug = {"
echo "     checkBloomberg: () => {"
echo "       const inv = window.componentInventory || import('/src/core/components/ComponentInventory.ts')"
echo "       console.log('All components:', inv.searchComponents(''))"
echo "       console.log('Bloomberg component:', inv.getComponent('bloomberg-volatility'))"
echo "       console.log('Categories:', inv.getCategories())"
echo "       return inv.getComponent('bloomberg-volatility')"
echo "     }"
echo "   }"
echo "   window.__componentDebug.checkBloomberg()"
echo ""
echo -e "\n3. If Bloomberg component is missing, run:"
echo "   docker-compose -f docker-compose.local.yml restart frontend"
echo ""
echo -e "\n4. Check frontend logs for errors:"
echo "   docker-compose -f docker-compose.local.yml logs frontend --tail 50"